/**
 * @module @laila/shared/constants/api
 *
 * API-related constants shared across services. These values define
 * the API versioning scheme, key format, and pagination defaults
 * used throughout the system.
 *
 * These are plain constants (not Zod schemas) because they represent
 * fixed configuration values rather than validatable enumerations.
 */

/**
 * Prefix for all API keys generated by the system.
 *
 * The `lw_` prefix enables:
 * - Quick visual identification of keys belonging to this service
 * - Efficient database lookups via a prefix column index
 * - Automated secret scanning tools to detect leaked keys
 */
export const API_KEY_PREFIX = 'lw_' as const;

/**
 * Current API version string used in URL path segments.
 *
 * All API endpoints are versioned under `/api/{API_VERSION}/...`
 * to support backward-compatible evolution of the API surface.
 */
export const API_VERSION = 'v1' as const;

/**
 * Default number of items returned per page when the client
 * does not specify a `limit` query parameter.
 */
export const DEFAULT_PAGINATION_LIMIT = 20 as const;

/**
 * Maximum number of items a client can request per page.
 *
 * Requests exceeding this limit will be clamped to this value
 * to protect against excessive memory and query costs.
 */
export const MAX_PAGINATION_LIMIT = 100 as const;
