/**
 * @module dynamo/audit-writer
 *
 * Audit event writer for persisting audit events to DynamoDB.
 *
 * Supports two write modes:
 * 1. **Single write** (`writeAuditEvent`) — for real-time audit logging during
 *    API request handling (e.g., entity created, status changed).
 * 2. **Batch write** (`writeAuditEventBatch`) — for bulk audit operations like
 *    cascade deletes or bulk status updates, using DynamoDB BatchWriteItem.
 *
 * TTL-based expiration is applied to all events. Retention period defaults to
 * 90 days and is configurable via the `AUDIT_RETENTION_DAYS` environment variable.
 */

import { randomUUID } from 'node:crypto';

import { PutCommand, BatchWriteCommand, type BatchWriteCommandOutput } from '@aws-sdk/lib-dynamodb';

import { createDynamoClient } from './client';
import { AUDIT_TABLE_NAME, CROSS_PROJECT_PK_VALUE, type AuditEventItem } from './schema';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_RETENTION_DAYS = 90;

/** DynamoDB BatchWriteItem accepts a maximum of 25 items per request. */
const BATCH_SIZE_LIMIT = 25;

/** Maximum number of retry attempts for unprocessed items in batch writes. */
const MAX_RETRIES = 3;

/** Base delay in milliseconds for exponential backoff between retries. */
const BASE_RETRY_DELAY_MS = 100;

// ---------------------------------------------------------------------------
// Input type
// ---------------------------------------------------------------------------

/**
 * Input type for writing an audit event.
 *
 * Excludes computed fields (sort key, eventId, timestamp, TTL) which are
 * generated by the writer at write time.
 */
export interface AuditEventInput {
  /** Type of entity: project, epic, user_story, task, worker, persona */
  entityType: string;

  /** Unique identifier of the entity that was acted upon */
  entityId: string;

  /** Action performed: created, updated, deleted, status_changed, assigned, completed */
  action: string;

  /** Type of actor: user, worker, system */
  actorType: 'user' | 'worker' | 'system';

  /** Unique identifier of the actor who performed the action */
  actorId: string;

  /** Tenant ID for multi-tenant access control */
  tenantId: string;

  /** Project ID for project-scoped queries — all entity events within a project share this */
  projectId?: string;

  /** Human-readable description of the event */
  details?: string;

  /** Before/after state for change tracking */
  changes?: { before?: Record<string, unknown>; after?: Record<string, unknown> };

  /** Additional context metadata */
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Custom error
// ---------------------------------------------------------------------------

/** Application-level error wrapping DynamoDB operation failures. */
export class AuditWriteError extends Error {
  public readonly cause: unknown;

  constructor(message: string, cause?: unknown) {
    super(message);
    this.name = 'AuditWriteError';
    this.cause = cause;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Reads the retention period from env, falling back to 90 days. */
const getRetentionDays = (): number => {
  const raw = process.env['AUDIT_RETENTION_DAYS'];
  if (raw === undefined) return DEFAULT_RETENTION_DAYS;
  const parsed = parseInt(raw, 10);
  return Number.isNaN(parsed) || parsed <= 0 ? DEFAULT_RETENTION_DAYS : parsed;
};

/** Required fields that must be present on every audit event input. */
const REQUIRED_FIELDS = [
  'entityType',
  'entityId',
  'action',
  'actorType',
  'actorId',
  'tenantId',
] as const;

/** Validates that all required fields are non-empty, non-whitespace strings. */
const validateInput = (input: AuditEventInput): void => {
  for (const field of REQUIRED_FIELDS) {
    const value = (input as unknown as Record<string, unknown>)[field];
    if (typeof value !== 'string' || value.trim() === '') {
      throw new AuditWriteError(`Missing required field: ${field}`);
    }
  }
};

/** Builds a complete DynamoDB item from an audit event input. */
const buildAuditItem = (input: AuditEventInput): AuditEventItem => {
  const eventId = randomUUID();
  const timestamp = new Date().toISOString();
  const retentionDays = getRetentionDays();

  return {
    entityId: `${input.entityType}:${input.entityId}`,
    'timestamp#eventId': `${timestamp}#${eventId}`,
    actorId: input.actorId,
    timestamp,
    eventId,
    entityType: input.entityType,
    action: input.action,
    actorType: input.actorType,
    tenantId: input.tenantId,
    gsi1pk: CROSS_PROJECT_PK_VALUE,
    ...(input.projectId !== undefined ? { projectId: input.projectId } : {}),
    ...(input.details !== undefined ? { details: input.details } : {}),
    ...(input.changes !== undefined ? { changes: input.changes } : {}),
    ...(input.metadata !== undefined ? { metadata: input.metadata } : {}),
    expiresAt: Math.floor(Date.now() / 1000) + retentionDays * 86400,
  };
};

/**
 * Waits for an exponentially increasing duration before retrying.
 *
 * Delay formula: baseDelay * 2^attempt (e.g., 100ms, 200ms, 400ms).
 */
const backoff = (attempt: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, BASE_RETRY_DELAY_MS * 2 ** attempt));

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Writes a single audit event to DynamoDB.
 *
 * Used for real-time audit logging during API request handling. Generates
 * the composite sort key, eventId, timestamp, and TTL automatically.
 *
 * @param input - The audit event input (without computed fields)
 * @returns The complete audit event item as written to DynamoDB
 * @throws {AuditWriteError} When validation fails or the DynamoDB write fails
 */
export const writeAuditEvent = async (input: AuditEventInput): Promise<AuditEventItem> => {
  validateInput(input);

  const item = buildAuditItem(input);

  try {
    const client = createDynamoClient();
    await client.send(
      new PutCommand({
        TableName: AUDIT_TABLE_NAME,
        Item: item,
      }),
    );
  } catch (error) {
    throw new AuditWriteError(
      `Failed to write audit event for ${item.entityId}: ${error instanceof Error ? error.message : String(error)}`,
      error,
    );
  }

  return item;
};

/**
 * Writes multiple audit events to DynamoDB using BatchWriteItem.
 *
 * Chunking strategy:
 *   DynamoDB limits BatchWriteItem to 25 items per request. This function
 *   splits the input array into chunks of 25 and sends each chunk as a
 *   separate BatchWriteItem request.
 *
 * Retry strategy for unprocessed items:
 *   DynamoDB may return UnprocessedItems when the table's provisioned
 *   throughput is exceeded. This function retries unprocessed items with
 *   exponential backoff (100ms, 200ms, 400ms) up to 3 attempts. Items
 *   still unprocessed after all retries are counted as failures.
 *
 * @param inputs - Array of audit event inputs to write
 * @returns The count of successfully written events
 * @throws {AuditWriteError} When validation fails or a DynamoDB operation fails
 */
export const writeAuditEventBatch = async (inputs: AuditEventInput[]): Promise<number> => {
  if (inputs.length === 0) return 0;

  // Validate all inputs before writing any
  for (const input of inputs) {
    validateInput(input);
  }

  const client = createDynamoClient();
  let written = 0;

  // Chunk into batches of 25 (DynamoDB BatchWriteItem limit)
  for (let i = 0; i < inputs.length; i += BATCH_SIZE_LIMIT) {
    const chunk = inputs.slice(i, i + BATCH_SIZE_LIMIT);
    const items = chunk.map(buildAuditItem);

    type WriteRequest = NonNullable<
      NonNullable<BatchWriteCommandOutput['UnprocessedItems']>[string]
    >[number];

    let writeRequests: WriteRequest[] = items.map((item) => ({
      PutRequest: { Item: item },
    }));

    let attempt = 0;

    // Retry loop for unprocessed items with exponential backoff
    while (writeRequests.length > 0 && attempt < MAX_RETRIES) {
      if (attempt > 0) {
        await backoff(attempt - 1);
      }

      try {
        const response = await client.send(
          new BatchWriteCommand({
            RequestItems: {
              [AUDIT_TABLE_NAME]: writeRequests,
            },
          }),
        );

        const unprocessed = response.UnprocessedItems?.[AUDIT_TABLE_NAME];
        const unprocessedCount = unprocessed?.length ?? 0;

        // Count items that were successfully written in this attempt
        written += writeRequests.length - unprocessedCount;

        if (unprocessedCount === 0 || unprocessed === undefined) {
          // All items in this chunk were written successfully
          break;
        }

        // Retry only the unprocessed items
        writeRequests = unprocessed;
        attempt += 1;
      } catch (error) {
        throw new AuditWriteError(
          `Batch write failed at chunk ${String(Math.floor(i / BATCH_SIZE_LIMIT) + 1)}: ${error instanceof Error ? error.message : String(error)}`,
          error,
        );
      }
    }

    // If unprocessed items remain after all retries, throw
    if (writeRequests.length > 0 && attempt >= MAX_RETRIES) {
      throw new AuditWriteError(
        `Batch write failed: ${String(writeRequests.length)} items remained unprocessed after ${String(MAX_RETRIES)} retries`,
      );
    }
  }

  return written;
};

// ---------------------------------------------------------------------------
// Fire-and-forget wrapper
// ---------------------------------------------------------------------------

/**
 * Writes an audit event without blocking the caller.
 *
 * This is the recommended entry point for audit logging during API request
 * handling. It calls `writeAuditEvent` internally but catches any errors
 * and logs them to stderr instead of propagating. The returned promise
 * resolves to `void` immediately from the caller's perspective (use
 * `void writeAuditEventFireAndForget(input)` to invoke without awaiting).
 *
 * @param input - The audit event input (without computed fields)
 */
export const writeAuditEventFireAndForget = (input: AuditEventInput): void => {
  writeAuditEvent(input).catch((error: unknown) => {
    const message = error instanceof Error ? error.message : 'Unknown audit write error';
    console.error(`[audit] Failed to write audit event (non-blocking): ${message}`);
  });
};
