/**
 * @laila/api-spec — barrel export
 *
 * Re-exports all generated TypeScript types from the OpenAPI specification
 * and a pre-configured openapi-fetch client factory.
 *
 * Types are generated by openapi-typescript from openapi.yaml.
 *
 * Usage:
 *   import type { paths, components, operations } from "@laila/api-spec";
 *   import { createApiClient } from "@laila/api-spec";
 */
export type * from '../generated/api.js';
export { createApiClient } from './client.js';
