/**
 * @module @laila/shared/schemas/api/epic
 *
 * Zod schemas for Epic API request bodies and responses.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, workStatus, version, timestamps).
 * - **Update** schema makes all create fields optional but keeps `version`
 *   required for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { epicSchema } from '../epic';

/**
 * Fields that are auto-generated by the system and must not appear
 * in create or update request bodies.
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  workStatus: true,
  version: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} as const;

/**
 * Request body for creating a new epic (POST /api/v1/epics).
 *
 * Derives from the full epic entity schema, removing all fields
 * that the server generates automatically.
 */
export const createEpicSchema = epicSchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create epic request body */
export type CreateEpic = z.infer<typeof createEpicSchema>;

/**
 * Request body for updating an existing epic (PATCH /api/v1/epics/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic
 * locking -- the server rejects the update if the version does not
 * match the current database row.
 */
export const updateEpicSchema = createEpicSchema.partial().extend({
  /** Current version of the resource, required for optimistic locking */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update epic request body */
export type UpdateEpic = z.infer<typeof updateEpicSchema>;

/**
 * Single-item API response wrapper for an epic entity.
 */
export const epicResponseSchema = z.object({
  data: epicSchema,
});

/** Inferred TypeScript type for a single epic API response */
export type EpicResponse = z.infer<typeof epicResponseSchema>;
