/**
 * @module @laila/shared/schemas/api/persona
 *
 * Zod schemas for Persona API request bodies and responses.
 *
 * Personas are project-scoped reference entities without soft-delete
 * or optimistic locking. Each persona describes a role and its
 * system prompt instructions for AI worker task execution.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, timestamps). Requires
 *   name, systemPrompt, and projectId. Description is optional.
 * - **Update** schema makes updatable fields optional. projectId
 *   cannot be changed after creation.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { personaSchema } from '../persona';

/**
 * Fields that are auto-generated by the system and must not appear
 * in create or update request bodies.
 *
 * - `id` and `tenantId` are assigned by the server
 * - `createdAt` and `updatedAt` are set by the database
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  createdAt: true,
  updatedAt: true,
} as const;

/**
 * Request body for creating a new persona (POST /api/v1/personas).
 *
 * Derives from the full persona entity schema, removing all fields
 * that the server generates automatically.
 *
 * Fields:
 * - `name` (required) — human-readable persona name (1-255 chars)
 * - `description` (optional) — short description (up to 2K chars)
 * - `systemPrompt` (required) — system prompt instructions (up to 50K chars)
 * - `projectId` (required) — UUID of the project this persona belongs to
 */
export const createPersonaSchema = personaSchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create persona request body */
export type CreatePersona = z.infer<typeof createPersonaSchema>;

/**
 * Request body for updating an existing persona (PATCH /api/v1/personas/:id).
 *
 * All fields from the create schema except projectId are optional so
 * clients can send partial updates. projectId cannot be changed after
 * creation. Personas do not use optimistic locking, so no `version`
 * field is required.
 */
export const updatePersonaSchema = createPersonaSchema.omit({ projectId: true }).partial();

/** Inferred TypeScript type for the update persona request body */
export type UpdatePersona = z.infer<typeof updatePersonaSchema>;

/**
 * Single-item API response wrapper for a persona entity.
 */
export const personaResponseSchema = z.object({
  data: personaSchema,
});

/** Inferred TypeScript type for a single persona API response */
export type PersonaResponse = z.infer<typeof personaResponseSchema>;
