/**
 * @module @laila/shared/schemas/api/persona
 *
 * Zod schemas for Persona API request bodies and responses.
 *
 * Personas are lightweight reference entities without soft-delete.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, timestamps).
 * - **Update** schema makes all create fields optional but requires
 *   a `version` field for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { personaSchema } from '../persona';

/**
 * Fields that are auto-generated by the system and must not appear
 * in create or update request bodies.
 *
 * - `id` and `tenantId` are assigned by the server
 * - `createdAt` and `updatedAt` are set by the database
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  createdAt: true,
  updatedAt: true,
} as const;

/**
 * Request body for creating a new persona (POST /api/v1/personas).
 *
 * Derives from the full persona entity schema, removing all fields
 * that the server generates automatically.
 */
export const createPersonaSchema = personaSchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create persona request body */
export type CreatePersona = z.infer<typeof createPersonaSchema>;

/**
 * Request body for updating an existing persona (PATCH /api/v1/personas/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic locking.
 */
export const updatePersonaSchema = createPersonaSchema.partial().extend({
  /** Current version for optimistic concurrency control */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update persona request body */
export type UpdatePersona = z.infer<typeof updatePersonaSchema>;

/**
 * Single-item API response wrapper for a persona entity.
 */
export const personaResponseSchema = z.object({
  data: personaSchema,
});

/** Inferred TypeScript type for a single persona API response */
export type PersonaResponse = z.infer<typeof personaResponseSchema>;
