/**
 * @module @laila/shared/schemas/api/project
 *
 * Zod schemas for Project API request bodies and responses.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, workStatus, version, timestamps).
 * - **Update** schema makes all create fields optional but keeps `version`
 *   required for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { projectSchema } from '../project';

/**
 * Fields that are auto-generated by the system and must not appear
 * in create or update request bodies.
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  workStatus: true,
  version: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} as const;

/**
 * Request body for creating a new project (POST /api/v1/projects).
 *
 * Derives from the full project entity schema, removing all fields
 * that the server generates automatically.
 */
export const createProjectSchema = projectSchema.omit(autoGeneratedFields).extend({
  /** Optional -- defaults to 30 on the database side when not provided */
  workerInactivityTimeoutMinutes: projectSchema.shape.workerInactivityTimeoutMinutes.optional(),
});

/** Inferred TypeScript type for the create project request body */
export type CreateProject = z.infer<typeof createProjectSchema>;

/**
 * Request body for updating an existing project (PATCH /api/v1/projects/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic
 * locking -- the server rejects the update if the version does not
 * match the current database row.
 */
export const updateProjectSchema = createProjectSchema.partial().extend({
  /** Current version of the resource, required for optimistic locking */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update project request body */
export type UpdateProject = z.infer<typeof updateProjectSchema>;

/**
 * Single-item API response wrapper for a project entity.
 */
export const projectResponseSchema = z.object({
  data: projectSchema,
});

/** Inferred TypeScript type for a single project API response */
export type ProjectResponse = z.infer<typeof projectResponseSchema>;
