/**
 * @module @laila/shared/schemas/api/task
 *
 * Zod schemas for Task API request bodies and responses.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, workStatus, version, timestamps)
 *   and extends with `dependencyIds` for DAG edge management.
 * - **Update** schema makes all create fields optional but keeps `version`
 *   required for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 * - **Detail response** includes resolved dependency/dependent summaries.
 */

import { z } from 'zod';

import { workStatusSchema } from '../../constants';
import { taskSchema } from '../task';

/**
 * Fields that are auto-generated by the system and must not appear
 * in create or update request bodies.
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  workStatus: true,
  startedAt: true,
  completedAt: true,
  version: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} as const;

/**
 * Request body for creating a new task (POST /api/v1/tasks).
 *
 * Derives from the full task entity schema, removing all fields
 * that the server generates automatically. Extends with:
 * - `dependencyIds` -- UUIDs of tasks this task depends on (DAG edges)
 */
export const createTaskSchema = taskSchema.omit(autoGeneratedFields).extend({
  /** Task UUIDs this task depends on (prerequisite tasks). Max 50. */
  dependencyIds: z.array(z.string().uuid()).max(50).default([]),
});

/** Inferred TypeScript type for the create task request body */
export type CreateTask = z.infer<typeof createTaskSchema>;

/**
 * Request body for updating an existing task (PATCH /api/v1/tasks/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic
 * locking -- the server rejects the update if the version does not
 * match the current database row.
 *
 * When `dependencyIds` is provided, the full dependency list is replaced
 * (not incremental add/remove). Omitting `dependencyIds` leaves
 * dependencies unchanged.
 */
export const updateTaskSchema = createTaskSchema.partial().extend({
  /** Current version of the resource, required for optimistic locking */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update task request body */
export type UpdateTask = z.infer<typeof updateTaskSchema>;

/**
 * Single-item API response wrapper for a task entity.
 */
export const taskResponseSchema = z.object({
  data: taskSchema,
});

/** Inferred TypeScript type for a single task API response */
export type TaskResponse = z.infer<typeof taskResponseSchema>;

/**
 * Summary of a task used in dependency/dependent resolution.
 * Contains only the fields needed for display in dependency lists.
 */
export const taskSummarySchema = z.object({
  id: z.string().uuid(),
  title: z.string(),
  workStatus: workStatusSchema,
});

/** Inferred TypeScript type for a task summary */
export type TaskSummary = z.infer<typeof taskSummarySchema>;

/**
 * Detailed task response for GET /api/v1/tasks/:id.
 * Includes the full task entity plus resolved dependency and
 * dependent summaries so the client can display meaningful
 * dependency information without additional requests.
 */
export const taskDetailResponseSchema = z.object({
  data: taskSchema.extend({
    /** Tasks this task depends on (prerequisites), resolved to summaries */
    dependencies: z.array(taskSummarySchema),
    /** Tasks that depend on this task (downstream), resolved to summaries */
    dependents: z.array(taskSummarySchema),
  }),
});

/** Inferred TypeScript type for a detailed task API response */
export type TaskDetailResponse = z.infer<typeof taskDetailResponseSchema>;
