/**
 * @module @laila/shared/schemas/api/task
 *
 * Zod schemas for Task API request bodies and responses.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, workStatus, version, timestamps).
 * - **Update** schema makes all create fields optional but keeps `version`
 *   required for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { taskSchema } from '../task';

/**
 * Fields that are auto-generated by the system and must not appear
 * in create or update request bodies.
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  workStatus: true,
  version: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} as const;

/**
 * Request body for creating a new task (POST /api/v1/tasks).
 *
 * Derives from the full task entity schema, removing all fields
 * that the server generates automatically.
 */
export const createTaskSchema = taskSchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create task request body */
export type CreateTask = z.infer<typeof createTaskSchema>;

/**
 * Request body for updating an existing task (PATCH /api/v1/tasks/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic
 * locking -- the server rejects the update if the version does not
 * match the current database row.
 */
export const updateTaskSchema = createTaskSchema.partial().extend({
  /** Current version of the resource, required for optimistic locking */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update task request body */
export type UpdateTask = z.infer<typeof updateTaskSchema>;

/**
 * Single-item API response wrapper for a task entity.
 */
export const taskResponseSchema = z.object({
  data: taskSchema,
});

/** Inferred TypeScript type for a single task API response */
export type TaskResponse = z.infer<typeof taskResponseSchema>;
