/**
 * @module @laila/shared/schemas/api/user-story
 *
 * Zod schemas for User Story API request bodies and responses.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, workStatus, version, timestamps)
 *   and system-managed assignment fields (assignedWorkerId, assignedAt,
 *   attempts, actualCost).
 * - **Update** schema makes all create fields optional but keeps `version`
 *   required for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { userStorySchema } from '../user-story';

/**
 * Fields that are auto-generated or system-managed and must not
 * appear in create request bodies.
 *
 * - `id`, `tenantId` are assigned by the server
 * - `workStatus` is managed by the state machine
 * - `version` is for optimistic locking (server-managed)
 * - `assignedWorkerId`, `assignedAt` are set during work assignment
 * - `attempts`, `actualCost` are tracked during execution
 * - `createdAt`, `updatedAt`, `deletedAt` are timestamps managed by the DB
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  workStatus: true,
  version: true,
  assignedWorkerId: true,
  assignedAt: true,
  attempts: true,
  actualCost: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} as const;

/**
 * Request body for creating a new user story (POST /api/v1/user-stories).
 *
 * Derives from the full user story entity schema, removing all fields
 * that the server generates or manages automatically. Clients provide:
 * epicId, title, description, priority, costEstimate, maxAttempts.
 */
export const createUserStorySchema = userStorySchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create user story request body */
export type CreateUserStory = z.infer<typeof createUserStorySchema>;

/**
 * Request body for updating an existing user story (PATCH /api/v1/user-stories/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic
 * locking -- the server rejects the update if the version does not
 * match the current database row.
 */
export const updateUserStorySchema = createUserStorySchema.partial().extend({
  /** Current version of the resource, required for optimistic locking */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update user story request body */
export type UpdateUserStory = z.infer<typeof updateUserStorySchema>;

/**
 * Single-item API response wrapper for a user story entity.
 */
export const userStoryResponseSchema = z.object({
  data: userStorySchema,
});

/** Inferred TypeScript type for a single user story API response */
export type UserStoryResponse = z.infer<typeof userStoryResponseSchema>;
