/**
 * @module @laila/shared/schemas/api/worker
 *
 * Zod schemas for Worker API request bodies and responses.
 *
 * The `isActive` and `lastSeenAt` fields are managed by the system
 * during heartbeat updates and are excluded from create requests.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, isActive, lastSeenAt, timestamps).
 * - **Update** schema makes all create fields optional but requires
 *   a `version` field for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { workerSchema } from '../worker';

/**
 * Fields that are auto-generated or system-managed and must not
 * appear in create request bodies.
 *
 * - `id` and `tenantId` are assigned by the server
 * - `isActive` defaults to true on creation, toggled via dedicated endpoints
 * - `lastSeenAt` is updated by the heartbeat mechanism
 * - `createdAt` and `updatedAt` are set by the database
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  isActive: true,
  lastSeenAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

/**
 * Request body for creating a new worker (POST /api/v1/workers).
 *
 * Derives from the full worker entity schema, removing all fields
 * that the server generates or manages automatically.
 */
export const createWorkerSchema = workerSchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create worker request body */
export type CreateWorker = z.infer<typeof createWorkerSchema>;

/**
 * Request body for updating an existing worker (PATCH /api/v1/workers/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic locking.
 */
export const updateWorkerSchema = createWorkerSchema.partial().extend({
  /** Current version for optimistic concurrency control */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update worker request body */
export type UpdateWorker = z.infer<typeof updateWorkerSchema>;

/**
 * Request body for updating worker name and/or description only
 * (PATCH /api/v1/workers/:id).
 *
 * Workers do not use integer-based optimistic locking (no `version` column),
 * so this schema omits the `version` field. The repository uses `updatedAt`
 * timestamp-based concurrency control instead.
 *
 * At least one field must be provided -- an empty object is rejected by the
 * `.refine()` check.
 */
export const updateWorkerBodySchema = z
  .object({
    /** Updated human-readable worker name */
    name: z.string().min(1).max(255).optional(),
    /** Updated description of the worker's purpose or capabilities */
    description: z.string().max(2000).nullable().optional(),
  })
  .refine((data) => data.name !== undefined || data.description !== undefined, {
    message: 'At least one of name or description must be provided',
  });

/** Inferred TypeScript type for the update worker body request */
export type UpdateWorkerBody = z.infer<typeof updateWorkerBodySchema>;

/**
 * Query parameters for the DELETE /api/v1/workers/:id endpoint.
 *
 * When `force` is true, the worker is deleted even if it has in-progress
 * story assignments. All assigned stories are unassigned first.
 */
export const deleteWorkerQuerySchema = z.object({
  /** Force deletion, unassigning all in-progress stories first */
  force: z
    .enum(['true', 'false'])
    .transform((val) => val === 'true')
    .optional()
    .default('false'),
});

/** Inferred TypeScript type for the delete worker query parameters */
export type DeleteWorkerQuery = z.infer<typeof deleteWorkerQuerySchema>;

/**
 * Single-item API response wrapper for a worker entity.
 */
export const workerResponseSchema = z.object({
  data: workerSchema,
});

/** Inferred TypeScript type for a single worker API response */
export type WorkerResponse = z.infer<typeof workerResponseSchema>;
