/**
 * @module @laila/shared/schemas/api/worker
 *
 * Zod schemas for Worker API request bodies and responses.
 *
 * The `isActive` and `lastSeenAt` fields are managed by the system
 * during heartbeat updates and are excluded from create requests.
 *
 * - **Create** schema derives from the entity schema by omitting
 *   auto-generated fields (id, tenantId, isActive, lastSeenAt, timestamps).
 * - **Update** schema makes all create fields optional but requires
 *   a `version` field for optimistic locking.
 * - **Response** schema wraps the entity for single-item API responses.
 */

import { z } from 'zod';

import { workerSchema } from '../worker';

/**
 * Fields that are auto-generated or system-managed and must not
 * appear in create request bodies.
 *
 * - `id` and `tenantId` are assigned by the server
 * - `isActive` defaults to true on creation, toggled via dedicated endpoints
 * - `lastSeenAt` is updated by the heartbeat mechanism
 * - `createdAt` and `updatedAt` are set by the database
 */
const autoGeneratedFields = {
  id: true,
  tenantId: true,
  isActive: true,
  lastSeenAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

/**
 * Request body for creating a new worker (POST /api/v1/workers).
 *
 * Derives from the full worker entity schema, removing all fields
 * that the server generates or manages automatically.
 */
export const createWorkerSchema = workerSchema.omit(autoGeneratedFields);

/** Inferred TypeScript type for the create worker request body */
export type CreateWorker = z.infer<typeof createWorkerSchema>;

/**
 * Request body for updating an existing worker (PATCH /api/v1/workers/:id).
 *
 * All fields from the create schema are optional so clients can send
 * partial updates. The `version` field is required for optimistic locking.
 */
export const updateWorkerSchema = createWorkerSchema.partial().extend({
  /** Current version for optimistic concurrency control */
  version: z.number().int().nonnegative(),
});

/** Inferred TypeScript type for the update worker request body */
export type UpdateWorker = z.infer<typeof updateWorkerSchema>;

/**
 * Single-item API response wrapper for a worker entity.
 */
export const workerResponseSchema = z.object({
  data: workerSchema,
});

/** Inferred TypeScript type for a single worker API response */
export type WorkerResponse = z.infer<typeof workerResponseSchema>;
